# Generated by Django 3.1.2 on 2020-10-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Noticias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='tipo_de_noticia',
            field=models.CharField(help_text='Debe indicar el tipo de noticia, por ejemplo novedad, popular etc.', max_length=50, null=True),
        ),
    ]
