# Generated by Django 3.1.2 on 2020-11-03 19:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Noticias', '0002_auto_20201026_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='correo',
            field=models.EmailField(error_messages={'Error': 'Digite un formato válido!'}, help_text='Indique el correo del Autor', max_length=50),
        ),
        migrations.AlterField(
            model_name='autor',
            name='educacion',
            field=models.CharField(choices=[('UV', 'Universidad'), ('TC', 'Tecnico Profesional'), ('SC', 'Secundaria Completa'), ('NA', 'Ninguno')], default='NA', help_text='Indique el nivel de estudios de Autor', max_length=2),
        ),
        migrations.AlterField(
            model_name='autor',
            name='id_autor',
            field=models.UUIDField(default=uuid.uuid4, help_text='Indique el ID del Autor de noticia', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='autor',
            name='nom_autor',
            field=models.CharField(help_text='Indique el nombre del Autor', max_length=25),
        ),
        migrations.AlterField(
            model_name='autor',
            name='numero',
            field=models.IntegerField(blank=True, help_text='Indique el número de contacto del Autor', null=True),
        ),
        migrations.AlterField(
            model_name='consola',
            name='generacion',
            field=models.CharField(help_text='Indique la Generación a la que pertenece la Consola', max_length=25),
        ),
        migrations.AlterField(
            model_name='consola',
            name='nombre',
            field=models.CharField(help_text='Indique el Nombre de la Consola', max_length=50),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='apellido',
            field=models.TextField(help_text='Indique los apellidos del postulante', max_length=50),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='area_postular',
            field=models.CharField(choices=[('NV', 'Noticias Videojuegos'), ('NC', 'Noticias Consolas'), ('PG', 'Publicidad Gaming')], default='NV', help_text='Indique el Areal a Postular', max_length=2),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='correo',
            field=models.EmailField(error_messages={'Error': 'Digite un formato válido!'}, help_text='Indique el correo del postulante', max_length=50),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='motivo',
            field=models.TextField(help_text='Motivo por el cual quiere ser parte del equipo', max_length=500),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='nivel_estudios',
            field=models.CharField(choices=[('UV', 'Universidad'), ('TC', 'Tecnico Profesional'), ('SC', 'Secundaria Completa'), ('NA', 'Ninguno')], default='NA', help_text='Indique el nivel de estudios del postulante', max_length=2),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='nombre',
            field=models.TextField(help_text='Indique el nombre del postulante', max_length=50),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='numero',
            field=models.IntegerField(blank=True, help_text='Indique el número de contacto del postulante', null=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='descripcion',
            field=models.TextField(help_text='Agrege una pequeña descripción de la noticia', max_length=100),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='titulo',
            field=models.CharField(help_text='Indique el titular de la noticia', max_length=50),
        ),
    ]
