# Generated by Django 3.1.2 on 2020-10-24 18:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Noticias', '0002_auto_20201018_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id_postulacion', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('area_postular', models.CharField(choices=[('NV', 'Noticias Videojuegos'), ('NC', 'Noticias Consolas'), ('PG', 'Publicidad Gaming')], default='NV', max_length=2)),
                ('nombre', models.TextField(max_length=50)),
                ('apellido', models.TextField(max_length=50)),
                ('correo', models.EmailField(error_messages={'Error': 'Digite un formato válido!'}, max_length=50)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('nivel_estudios', models.CharField(choices=[('UV', 'Universidad'), ('TC', 'Tecnico Profesional'), ('SC', 'Secundaria Completa'), ('NA', 'Ninguno')], default='NA', max_length=2)),
                ('motivo', models.TextField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='autor',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
